// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import * as THREE from "three";
// type SkateboardProps = {
//   wheelTextureURLs: string[];
//   wheelTextureURL: string;
//   deckTextureURLs: string[];
//   deckTextureURL: string;
//   truckColor: string;
//   boltColor: string;
//   constantWheelSpin?: boolean;
//   pose?: "upright" | "side";
// };

// type GLTFResult = GLTF & {
//   nodes: {
//     GripTape: THREE.Mesh;
//     Wheel1: THREE.Mesh;
//     Wheel2: THREE.Mesh;
//     Deck: THREE.Mesh;
//     Wheel4: THREE.Mesh;
//     Bolts: THREE.Mesh;
//     Wheel3: THREE.Mesh;
//     Baseplates: THREE.Mesh;
//     Truck1: THREE.Mesh;
//     Truck2: THREE.Mesh;
//   };
//   materials: object;
// };
// export function Skateboard(props: SkateboardProps) {
//   const { nodes, materials } = useGLTF("/skateboard.gltf");
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.GripTape.geometry}
//         material={nodes.GripTape.material}
//         position={[0, 0.286, -0.002]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel1.geometry}
//         material={nodes.Wheel1.material}
//         position={[0.238, 0.086, 0.635]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel2.geometry}
//         material={nodes.Wheel2.material}
//         position={[-0.237, 0.086, 0.635]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Deck.geometry}
//         material={nodes.Deck.material}
//         position={[0, 0.271, -0.002]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel4.geometry}
//         material={nodes.Wheel4.material}
//         position={[-0.238, 0.086, -0.635]}
//         rotation={[Math.PI, 0, Math.PI]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Bolts.geometry}
//         material={nodes.Bolts.material}
//         position={[0, 0.198, 0]}
//         rotation={[Math.PI, 0, Math.PI]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel3.geometry}
//         material={nodes.Wheel3.material}
//         position={[0.237, 0.086, -0.635]}
//         rotation={[Math.PI, 0, Math.PI]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Baseplates.geometry}
//         material={nodes.Baseplates.material}
//         position={[0, 0.211, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Truck1.geometry}
//         material={nodes.Truck1.material}
//         position={[0, 0.101, -0.617]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Truck2.geometry}
//         material={nodes.Truck2.material}
//         position={[0, 0.101, 0.617]}
//         rotation={[Math.PI, 0, Math.PI]}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/skateboard.gltf");
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type SkateboardProps = {
  wheelTextureURLs: string[];
  wheelTextureURL: string;
  deckTextureURLs: string[];
  deckTextureURL: string;
  truckColor: string;
  boltColor: string;
  constantWheelSpin?: boolean;
  pose?: "upright" | "side";
};

type GLTFResult = GLTF & {
  nodes: {
    GripTape: THREE.Mesh;
    Wheel1: THREE.Mesh;
    Wheel2: THREE.Mesh;
    Deck: THREE.Mesh;
    Wheel4: THREE.Mesh;
    Bolts: THREE.Mesh;
    Wheel3: THREE.Mesh;
    Baseplates: THREE.Mesh;
    Truck1: THREE.Mesh;
    Truck2: THREE.Mesh;
  };
  materials: {
    [name: string]: THREE.Material;
  };
};

export function Skateboard({
  wheelTextureURLs,
  wheelTextureURL,
  deckTextureURLs,
  deckTextureURL,
  truckColor,
  boltColor,
  constantWheelSpin,
  pose,
}: SkateboardProps) {
  const { nodes, materials } = useGLTF("/skateboard.gltf") as GLTFResult;

  // Optional: Apply dynamic color or texture logic here
  // Example:
  // materials.Truck1.color.set(truckColor);
  // materials.Bolts.color.set(boltColor);
  const GripTapeDiffuse = useTexture("/skateboard/griptape-diffuse.webp");
  const gripTapeRoughness = useTexture("/skateboard/griptape-roughness.webp");

  return (
    <group dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GripTape.geometry}
        material={nodes.GripTape.material}
        position={[0, 0.286, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel1.geometry}
        material={nodes.Wheel1.material}
        position={[0.238, 0.086, 0.635]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel2.geometry}
        material={nodes.Wheel2.material}
        position={[-0.237, 0.086, 0.635]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Deck.geometry}
        material={nodes.Deck.material}
        position={[0, 0.271, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel4.geometry}
        material={nodes.Wheel4.material}
        position={[-0.238, 0.086, -0.635]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolts.geometry}
        material={nodes.Bolts.material}
        position={[0, 0.198, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel3.geometry}
        material={nodes.Wheel3.material}
        position={[0.237, 0.086, -0.635]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Baseplates.geometry}
        material={nodes.Baseplates.material}
        position={[0, 0.211, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Truck1.geometry}
        material={nodes.Truck1.material}
        position={[0, 0.101, -0.617]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Truck2.geometry}
        material={nodes.Truck2.material}
        position={[0, 0.101, 0.617]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/skateboard.gltf");
